# FamilyShield Docker Compose Stack
# Environment: ${environment}
# Generated by OpenTofu — do not edit manually on server
# Source: iac/templates/docker-compose.yaml.tpl
# Year: 2026

version: "3.9"

networks:
  familyshield:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  adguard_work:
  adguard_conf:
  headscale_data:
  influxdb_data:
  grafana_data:
  mitmproxy_data:
  redis_data:

services:

  # ── 1. AdGuard Home — DNS filtering + per-device profiles ──────────────────
  adguard:
    image: adguard/adguardhome:latest
    container_name: familyshield-adguard
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3080:80/tcp"     # Admin UI (exposed via Cloudflare Tunnel)
      - "443:443/tcp"     # DoH
      - "853:853/tcp"     # DoT
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    environment:
      - TZ=America/Toronto
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 2. Headscale — Self-hosted Tailscale control plane ────────────────────
  headscale:
    image: headscale/headscale:latest
    container_name: familyshield-headscale
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.3
    ports:
      - "8080:8080"       # Control plane (via Cloudflare Tunnel)
      - "9090:9090"       # Metrics
    volumes:
      - headscale_data:/var/lib/headscale
      - ./apps/platform-config/headscale/headscale.yaml:/etc/headscale/config.yaml:ro
    command: headscale serve
    environment:
      - TZ=America/Toronto
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9090/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 3. mitmproxy — SSL inspection + content ID extraction ─────────────────
  mitmproxy:
    image: mitmproxy/mitmproxy:latest
    container_name: familyshield-mitmproxy
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.4
    ports:
      - "8888:8080"       # mitmproxy web UI (Cloudflare Tunnel)
      - "8889:8081"       # Transparent proxy port
    volumes:
      - mitmproxy_data:/home/mitmproxy/.mitmproxy
      - ./apps/mitm:/addon:ro
    command: >
      mitmweb
      --mode transparent
      --web-host 0.0.0.0
      --web-port 8080
      --scripts /addon/familyshield_addon.py
    environment:
      - TZ=America/Toronto
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=${environment}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 4. Redis — Event queue between mitmproxy and enrichment worker ─────────
  redis:
    image: redis:7-alpine
    container_name: familyshield-redis
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.5
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── 5. API / Enrichment Worker — Platform API calls + AI risk scoring ──────
  api:
    image: ghcr.io/everythingcloudsolutions/familyshield-api:${environment}
    container_name: familyshield-api
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.6
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${environment}
      - TZ=America/Toronto
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${supabase_url}
      - SUPABASE_ANON_KEY=${supabase_anon_key}
      - SUPABASE_SERVICE_ROLE_KEY=${supabase_service_role_key}
      - GROQ_API_KEY=${groq_api_key}
      - ANTHROPIC_API_KEY=${anthropic_api_key}
      - YOUTUBE_API_KEY=$${YOUTUBE_API_KEY}
      - TWITCH_CLIENT_ID=$${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=$${TWITCH_CLIENT_SECRET}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  # ── 6. Portal — Next.js parent UI ──────────────────────────────────────────────
  portal:
    image: ghcr.io/everythingcloudsolutions/familyshield-portal:${environment}
    container_name: familyshield-portal
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.12
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${environment}
      - TZ=America/Toronto
      - NEXT_PUBLIC_SUPABASE_URL=${supabase_url}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabase_anon_key}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 7. Node-RED — Rule engine / flow automation ────────────────────────────
  nodered:
    image: nodered/node-red:latest
    container_name: familyshield-nodered
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.7
    ports:
      - "1880:1880"
    volumes:
      - ./apps/platform-config/nodered:/data
    environment:
      - TZ=America/Toronto
      - NODE_RED_ENABLE_PROJECTS=true
    depends_on:
      - redis
      - api

  # ── 8. InfluxDB — Time-series metrics storage ──────────────────────────────
  influxdb:
    image: influxdb:2.7-alpine
    container_name: familyshield-influxdb
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=$${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=familyshield
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - TZ=America/Toronto
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 9. Grafana — Usage dashboards ─────────────────────────────────────────
  grafana:
    image: grafana/grafana:latest
    container_name: familyshield-grafana
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.9
    ports:
      - "3002:3000"       # Admin UI (via Cloudflare Tunnel → Zero Trust)
    volumes:
      - grafana_data:/var/lib/grafana
      - ./apps/platform-config/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=https://grafana-${environment}.everythingcloud.ca
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - TZ=America/Toronto
    depends_on:
      influxdb:
        condition: service_healthy

  # ── 10. ntfy — Push notification server ────────────────────────────────────
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: familyshield-ntfy
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.10
    ports:
      - "2586:80"
    command: serve
    environment:
      - TZ=America/Toronto
      - NTFY_BASE_URL=https://notify-${environment}.everythingcloud.ca
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    volumes:
      - ./apps/platform-config/ntfy:/etc/ntfy:ro

  # ── 11. Cloudflare Tunnel daemon ──────────────────────────────────────────
  # NOTE: cloudflared is intentionally NOT managed by docker-compose.
  # It is started via `docker run --restart unless-stopped --token $TUNNEL_TOKEN`
  # in the infra workflow's setup-cloudflare job. The real tunnel token is only
  # known after Cloudflare IaC runs — it cannot be baked into this compose file.
  # Docker's own restart policy keeps it running across container restarts and reboots.
  # Running `docker compose up/restart` will NOT touch the tunnel container.
