# FamilyShield Docker Compose Stack
# Environment: ${environment}
# Generated by OpenTofu — do not edit manually on server
# Source: iac/templates/docker-compose.yaml.tpl
# Year: 2026

networks:
  familyshield:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

# All service data is stored on the OCI persistent block volume at /opt/familyshield-data.
# This volume survives VM recreation — AdGuard config, Headscale keys, InfluxDB data, etc. persist.
# DO NOT use Docker named volumes for stateful services — those live on the boot volume and are wiped.
# The infra workflow (infra-dev/prod.yml) formats + mounts the volume on first deploy.

services:

  # ── 1. AdGuard Home — DNS filtering + per-device profiles ──────────────────
  adguard:
    image: adguard/adguardhome:latest
    container_name: familyshield-adguard
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3080:80/tcp"     # Admin UI (exposed via Cloudflare Tunnel)
      - "853:853/tcp"     # DoT (Caddy uses port 443 for HTTPS reverse proxy)
    volumes:
      - /opt/familyshield-data/adguard/work:/opt/adguardhome/work
      - /opt/familyshield-data/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=America/Toronto
    healthcheck:
      # AdGuard admin UI is on port 80 AFTER setup wizard completes.
      # On first launch the wizard runs on port 3000 — this healthcheck will
      # correctly show UNHEALTHY until the one-time setup is done (expected).
      # To complete first-time setup: SSH port-forward → http://localhost:3000
      #   ssh -L 3000:localhost:3000 -i ~/.ssh/familyshield ubuntu@<vm-ip>
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 2. Headscale — Self-hosted Tailscale control plane ────────────────────
  headscale:
    image: headscale/headscale:latest
    container_name: familyshield-headscale
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.3
    ports:
      - "8080:8080"       # Control plane (via Cloudflare Tunnel)
      - "9090:9090"       # Metrics
    volumes:
      - /opt/familyshield-data/headscale:/var/lib/headscale
      - ./apps/platform-config/headscale/headscale.yaml:/etc/headscale/config.yaml:ro
    command: serve
    environment:
      - TZ=America/Toronto
      # Override the static config's server_url so Headscale advertises the correct
      # public HTTPS address to Tailscale clients. Without this, clients get
      # http://0.0.0.0:8080 from headscale.yaml and cannot reach the server.
      - HEADSCALE_SERVER_URL=https://vpn${env_suffix}.everythingcloud.ca
    healthcheck:
      # headscale uses a distroless base image — no wget/curl/nc available.
      # Use the headscale binary itself as a liveness check.
      test: ["CMD", "headscale", "version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 2b. Caddy — HTTPS reverse proxy for Headscale (Noise protocol + WebSocket) ──
  # Listens on 0.0.0.0:443, proxies to Headscale localhost:8080 with WebSocket support.
  # DNS A record (vpn${env_suffix}.everythingcloud.ca) points directly to OCI public IP,
  # bypassing Cloudflare Tunnel to preserve HTTP Upgrade headers required by Tailscale.
  caddy:
    image: caddy:latest
    container_name: familyshield-caddy
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.11
    ports:
      - "443:443/tcp"
      - "443:443/udp"       # QUIC
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/lib/caddy:/data/caddy
    depends_on:
      headscale:
        condition: service_started
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # ── 3. mitmproxy — SSL inspection + content ID extraction ─────────────────
  # Custom image (built from apps/mitm/Dockerfile) includes redis Python package.
  # Addon code is volume-mounted for live updates without image rebuild.
  mitmproxy:
    image: ghcr.io/everythingcloudsolutions/familyshield-mitm:${environment}
    container_name: familyshield-mitmproxy
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.4
    ports:
      - "8888:8080"       # mitmproxy web UI (Cloudflare Tunnel)
      - "8889:8081"       # Transparent proxy port
    volumes:
      - /opt/familyshield-data/mitmproxy:/home/mitmproxy/.mitmproxy
      # Note: addon code is baked into the image (COPY in Dockerfile).
      # No host volume mount — the ./apps/mitm directory does not exist on the server.
    environment:
      - TZ=America/Toronto
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=${environment}
    depends_on:
      - redis
    healthcheck:
      # mitmproxy web UI returns 403 without an auth token; urllib raises HTTPError for 4xx.
      # Use a raw TCP connect to the listen port (8081) instead — proves the proxy is up.
      test: ["CMD", "python3", "-c", "import socket; s=socket.socket(); s.settimeout(5); s.connect(('127.0.0.1',8081)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 4. Redis — Event queue between mitmproxy and enrichment worker ─────────
  redis:
    image: redis:7-alpine
    container_name: familyshield-redis
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.5
    volumes:
      - /opt/familyshield-data/redis:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── 5. API / Enrichment Worker — Platform API calls + AI risk scoring ──────
  api:
    image: ghcr.io/everythingcloudsolutions/familyshield-api:${environment}
    container_name: familyshield-api
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.6
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${environment}
      - TZ=America/Toronto
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${supabase_url}
      - SUPABASE_ANON_KEY=${supabase_anon_key}
      - SUPABASE_SERVICE_ROLE_KEY=${supabase_service_role_key}
      - GROQ_API_KEY=${groq_api_key}
      - ANTHROPIC_API_KEY=${anthropic_api_key}
      - YOUTUBE_API_KEY=${youtube_api_key}
      - DISCORD_BOT_TOKEN=${discord_bot_token}
      - TWITCH_CLIENT_ID=${twitch_client_id}
      - TWITCH_CLIENT_SECRET=${twitch_client_secret}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  # ── 6. Portal — Next.js parent UI ──────────────────────────────────────────────
  portal:
    image: ghcr.io/everythingcloudsolutions/familyshield-portal:${environment}
    container_name: familyshield-portal
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.12
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${environment}
      - TZ=America/Toronto
      - NEXT_PUBLIC_SUPABASE_URL=${supabase_url}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabase_anon_key}
      # Next.js standalone binds to Docker's HOSTNAME env var (container IP) by default.
      # Setting 0.0.0.0 ensures healthcheck (localhost:3000) and port mapping work correctly.
      - HOSTNAME=0.0.0.0
      # Auth: disabled for dev. In prod, set PORTAL_BASIC_AUTH_ENABLED=true and supply credentials.
      - PORTAL_BASIC_AUTH_ENABLED=false
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      # Use 127.0.0.1 not localhost — Alpine resolves localhost to ::1 (IPv6)
      # but Next.js standalone binds IPv4 only.
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 7. Node-RED — Rule engine / flow automation ────────────────────────────
  nodered:
    image: nodered/node-red:latest
    container_name: familyshield-nodered
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.7
    ports:
      - "1880:1880"
    volumes:
      - ./apps/platform-config/nodered:/data
    environment:
      - TZ=America/Toronto
      - NODE_RED_ENABLE_PROJECTS=true
    depends_on:
      - redis
      - api

  # ── 8. InfluxDB — Time-series metrics storage ──────────────────────────────
  influxdb:
    image: influxdb:2.7-alpine
    container_name: familyshield-influxdb
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.8
    ports:
      - "8086:8086"
    volumes:
      - /opt/familyshield-data/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${influxdb_password}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${influxdb_admin_token}
      - DOCKER_INFLUXDB_INIT_ORG=familyshield
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - TZ=America/Toronto
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 9. Grafana — Usage dashboards ─────────────────────────────────────────
  grafana:
    image: grafana/grafana:latest
    container_name: familyshield-grafana
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.9
    ports:
      - "3002:3000"       # Admin UI (via Cloudflare Tunnel → Zero Trust)
    volumes:
      - /opt/familyshield-data/grafana:/var/lib/grafana
      - ./apps/platform-config/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_password}
      - GF_SERVER_ROOT_URL=https://grafana${env_suffix}.everythingcloud.ca
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - INFLUXDB_ADMIN_TOKEN=${influxdb_admin_token}
      - TZ=America/Toronto
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ── 10. ntfy — Push notification server ────────────────────────────────────
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: familyshield-ntfy
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.10
    ports:
      - "2586:80"
    command: serve
    environment:
      - TZ=America/Toronto
      - NTFY_BASE_URL=https://notify${env_suffix}.everythingcloud.ca
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    volumes:
      - ./apps/platform-config/ntfy:/etc/ntfy:ro
      - /opt/familyshield-data/ntfy/cache:/var/cache/ntfy
      - /opt/familyshield-data/ntfy/data:/var/lib/ntfy

  # ── 11. Portainer — Docker management UI ──────────────────────────────────
  # Exposed via Cloudflare Tunnel (portainer${env_suffix}.everythingcloud.ca → localhost:9000)
  # Protected by Cloudflare Zero Trust (admin email OTP + service token for CI).
  # Provides full container management: start/stop/restart, logs, exec, image pulls.
  # Persistent data on block volume so admin users and settings survive VM recreation.
  portainer:
    image: portainer/portainer-ce:latest
    container_name: familyshield-portainer
    restart: unless-stopped
    networks:
      familyshield:
        ipv4_address: 172.20.0.13
    ports:
      - "9000:9000"   # HTTP UI — exposed via Cloudflare Tunnel only (no direct internet)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/familyshield-data/portainer:/data
    environment:
      - TZ=America/Toronto
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # ── 12. Cloudflare Tunnel daemon ──────────────────────────────────────────
  # NOTE: cloudflared is intentionally NOT managed by docker-compose.
  # It is started via `docker run --restart unless-stopped --token $TUNNEL_TOKEN`
  # in the infra workflow's setup-cloudflare job. The real tunnel token is only
  # known after Cloudflare IaC runs — it cannot be baked into this compose file.
  # Docker's own restart policy keeps it running across container restarts and reboots.
  # Running `docker compose up/restart` will NOT touch the tunnel container.
