{{/*
  FamilyShield Cloudflare Tunnel Configuration
  Generated by OpenTofu — Tunnel routes for all backend services
  Environment: ${environment}
  Year: 2026
*/}}

tunnel: familyshield-${environment}
credentials-file: /etc/cloudflare/credentials-${environment}.json

ingress:
  # SSH access (GitHub Actions deployment only)
  - hostname: ssh.familyshield-${environment}.everythingcloud.ca
    service: ssh://localhost:22

  # Portal (Next.js frontend)
  - hostname: familyshield-${environment}.everythingcloud.ca
    service: http://portal:3000

  # API health endpoint
  - hostname: api-${environment}.everythingcloud.ca
    service: http://api:3001

  # AdGuard Admin UI
  - hostname: adguard-${environment}.everythingcloud.ca
    service: http://adguard:3080

  # mitmproxy Web UI
  - hostname: mitmproxy-${environment}.everythingcloud.ca
    service: http://mitmproxy:8080

  # Headscale VPN Control Plane
  - hostname: vpn.familyshield-${environment}.everythingcloud.ca
    service: http://headscale:8080

  # Grafana Dashboards
  - hostname: grafana-${environment}.everythingcloud.ca
    service: http://grafana:3000

  # Node-RED Automation Platform
  - hostname: nodered-${environment}.everythingcloud.ca
    service: http://nodered:1880

  # Catch-all (default to portal if no match)
  - service: http_status:404
